<!-- Empty State -->
<div class="empty-state">
    <div class="empty-state__icon">
        <i class="fa fa-5x fa-{{ icon }}"></i>
    </div>
    <div class="text-center">
        <h2>Nada por aquí...</h2>
        <p class="empty-state__description"><?php echo $description ?></p>
        <?php if (AuthHelper::isLogged()) : ?>
            <?php if ($type == 'pet') : ?>
                <?php if (empty($owners)) : ?>
                    <p class="empty-state__description">Para agregar una mascota, debes tener dueños registrados</p>
                    <a href="<?= BASE_URL ?>add-owner" class="btn btn-primary">Agregar dueño</a>    
                <?php else : ?>
                    <a href="<?= BASE_URL ?>add-pet" class="btn btn-primary">Agregar mascota</a>
                <?php endif ?>
            <?php endif ?>
            <?php if ($type == 'owner') : ?>
                <a href="<?= BASE_URL ?>add-owner" class="btn btn-primary">Agregar dueño</a>
            <?php endif ?>

        <?php else : ?>
            <p class="empty-state__description">Para agregar, debes iniciar sesión</p>
            <a href="<?= BASE_URL ?>login" class="btn btn-primary">Iniciar sesión</a>
        <?php endif ?>
    </div>
</div>