<!-- Empty State -->
<div class="empty-state">
    <!-- <div class="empty-state__icon">
        <i class="fa fa-5x fa-{{ icon }}"></i>
    </div> -->
    <div class="empty-state__title">Nada por aquí...</div>
    <div class="empty-state__description"><?php echo $description ?></div>
    <div class="empty-state__action">
        <a href="../home" class="btn btn-primary">Ir al inicio</a>
    </div>

