<?php require_once 'templates/header.phtml' ?>
<div class="go-back">
    <a href="javascript:history.back()" class="btn btn-outline-primary">Volver a la página anterior</a>
</div>
<h2 style="margin-bottom: 20px;"><?php echo isset($item) ? 'Editar' : 'Crear'; ?> <?php echo $itemType == 'pet' ? 'Mascota' : 'Dueño'; ?></h2>

<?php if ($itemType == 'pet') : ?>

    <form class="formSubmit" id="pet" action="<?php echo isset($item) ? BASE_URL . 'update-pet/' . $item->ID  : BASE_URL . 'create-pet'; ?>" method="post">
    <?php endif; ?>
    <?php if ($itemType == 'owner') : ?>
        <form class="formSubmit" id="owner" action="<?php echo isset($item) ? BASE_URL . 'update-owner/' . $item->ID  : BASE_URL . 'create-owner'; ?>" method="post">
        <?php endif; ?>

        <?php if (isset($item)) : ?>
            <input type="hidden" name="<?php echo $itemType; ?>_id" value="<?php echo $item->ID; ?>">
        <?php endif; ?>

        <label for="name">Nombre:</label><br>
        <input class="form-control" type="text" id="name" name="name" value="<?php echo isset($item) ? $item->NOMBRE : ''; ?>"><br><br>

        <?php if ($itemType == 'owner') : ?>
            <label for="phone">Teléfono:</label><br>
            <input class="form-control" type="text" id="phone" name="phone" value="<?php echo isset($item) ? $item->TELEFONO : ''; ?>"><br><br>
            <label for="email">Correo electrónico:</label><br>
            <input class="form-control" type="text" id="email" name="email" value="<?php echo isset($item) ? $item->MAIL : ''; ?>"><br><br>
        <?php elseif ($itemType == 'pet') : ?>

            <label for="age">Edad:</label><br>
            <input class="form-control" type="text" id="age" name="age" value="<?php echo isset($item) ? $item->EDAD : ''; ?>"><br><br>

            <label for="weight">Peso (kg):</label><br>
            <input class="form-control" type="text" id="weight" name="weight" value="<?php echo isset($item) ? $item->PESO : ''; ?>"><br><br>

            <label for="type">Tipo:</label><br>
            <!-- <input type="text" id="type" name="type" value="<?php echo isset($item) ? $item->TIPO : ''; ?>"><br><br> -->
            <select class="form-control" name="type" id="type">
                <option value="Perro" <?php echo isset($item) && $item->TIPO == 'Perro' ? 'selected' : ''; ?>>Perro</option>
                <option value="Gato" <?php echo isset($item) && $item->TIPO == 'Gato' ? 'selected' : ''; ?>>Gato</option>
                <option value="Pez" <?php echo isset($item) && $item->TIPO == 'Pez' ? 'selected' : ''; ?>>Pez</option>
                <option value="Ave" <?php echo isset($item) && $item->TIPO == 'Ave' ? 'selected' : ''; ?>>Ave</option>
                <option value="Reptil" <?php echo isset($item) && $item->TIPO == 'Reptil' ? 'selected' : ''; ?>>Reptil</option>
            </select><br><br>

            <label for="owner">Dueño:</label><br>
            <select class="form-control" name="idowner" id="owner">
                <?php foreach ($owners as $owner) : ?>
                    <option value="<?php echo $owner->ID; ?>" <?php echo isset($item) && $item->ID_DUENIO == $owner->ID ? 'selected' : ''; ?>><?php echo $owner->NOMBRE .' '. '(' . $owner->MAIL . ')'; ?></option>
                <?php endforeach; ?>
            <?php endif; ?>
            </select><br><br>
            <button type="submit" onsubmit="formSubmit" class="btn btn-primary"><?php echo isset($item) ? 'Actualizar' : 'Crear'; ?> <?php echo $itemType == 'pet' ? 'Mascota' : 'Dueño'; ?></button>

        </form>
        <?php require_once 'templates/footer.phtml' ?>