<?php require_once 'templates/header.phtml' ?>
<?php require_once 'templates/navbar.phtml' ?>

<h2><?php echo isset($item) ? 'Editar' : 'Crear'; ?> <?php echo $itemType; ?></h2>
<form action="<?php echo isset($item) ? '/update_' . $itemType . '.php' : '/create_' . $itemType . '.php'; ?>" method="post">
    <?php if (isset($item)) : ?>
        <input type="hidden" name="<?php echo $itemType; ?>_id" value="<?php echo $item['id']; ?>">
    <?php endif; ?>
    <label for="name">Nombre:</label><br>
    <input type="text" id="name" name="name" value="<?php echo isset($item) ? $item['name'] : ''; ?>"><br><br>
    <label for="age">Edad:</label><br>
    <input type="text" id="age" name="age" value="<?php echo isset($item) ? $item['age'] : ''; ?>"><br><br>
    <?php if ($itemType == 'owner') : ?>
        <label for="phone">Teléfono:</label><br>
        <input type="text" id="phone" name="phone" value="<?php echo isset($item) ? $item['phone'] : ''; ?>"><br><br>
        <label for="email">Correo electrónico:</label><br>
        <input type="text" id="email" name="email" value="<?php echo isset($item) ? $item['email'] : ''; ?>"><br><br>
    <?php elseif ($itemType == 'pet') : ?>
        <label for="weight">Peso:</label><br>
        <input type="text" id="weight" name="weight" value="<?php echo isset($item) ? $item['weight'] : ''; ?>"><br><br>
        <label for="type">Tipo:</label><br>
        <input type="text" id="type" name="type" value="<?php echo isset($item) ? $item['type'] : ''; ?>"><br><br>
    <?php endif; ?>
    <input type="submit" value="<?php echo isset($item) ? 'Actualizar' : 'Crear'; ?> <?php echo $itemType; ?>">
</form>

<?php require_once 'templates/footer.phtml' ?>