<?php require_once 'templates/header.phtml' ?>
<div class="go-back">
    <a href="javascript:history.back()" class="btn btn-outline-primary">Volver a la página anterior</a>
</div>
<h2 style="margin-bottom: 20px;"><?php echo isset($item) ? 'Editar' : 'Crear'; ?> <?php echo $itemType == 'pet' ? 'Mascota' : 'Dueño'; ?></h2>

<?php if ($itemType == 'pet') : ?>

    <form class="formCreateEdit" id="pet" action="<?php echo isset($item) ? BASE_URL . 'update-pet/' . $item->ID  : BASE_URL . 'create-pet'; ?>" method="post">
    <?php endif; ?>
    <?php if ($itemType == 'owner') : ?>
        <form class="formCreateEdit" id="owner" action="<?php echo isset($item) ? BASE_URL . 'update-owner/' . $item->ID  : BASE_URL . 'create-owner'; ?>" method="post">
        <?php endif; ?>

        <?php if (isset($item)) : ?>
            <input type="hidden" name="<?php echo $itemType; ?>_id" value="<?php echo $item->ID; ?>">
        <?php endif; ?>

        <label for="name">Nombre:</label><br>
        <input class="form-control" type="text" id="name" name="name" value="<?php echo isset($item) ? $item->NOMBRE : ''; ?>"><br><br>

        <?php if ($itemType == 'owner') : ?>
            <label for="phone">Teléfono:</label><br>
            <input class="form-control" type="text" id="phone" name="phone" value="<?php echo isset($item) ? $item->TELEFONO : ''; ?>"><br><br>
            <label for="email">Correo electrónico:</label><br>
            <input class="form-control" type="text" id="email" name="email" value="<?php echo isset($item) ? $item->MAIL : ''; ?>"><br><br>
        <?php elseif ($itemType == 'pet') : ?>

            <label for="age">Edad:</label><br>
            <input class="form-control" type="text" id="age" name="age" value="<?php echo isset($item) ? $item->EDAD : ''; ?>"><br><br>

            <label for="weight">Peso:</label><br>
            <input class="form-control" type="text" id="weight" name="weight" value="<?php echo isset($item) ? $item->PESO : ''; ?>"><br><br>

            <label for="type">Tipo:</label><br>
            <!-- <input type="text" id="type" name="type" value="<?php echo isset($item) ? $item->TIPO : ''; ?>"><br><br> -->
            <select class="form-control" name="type" id="type">
                <option value="Perro" <?php echo isset($item) && $item->TIPO == 'Perro' ? 'selected' : ''; ?>>Perro</option>
                <option value="Gato" <?php echo isset($item) && $item->TIPO == 'Gato' ? 'selected' : ''; ?>>Gato</option>
                <option value="Pez" <?php echo isset($item) && $item->TIPO == 'Pez' ? 'selected' : ''; ?>>Pez</option>
                <option value="Ave" <?php echo isset($item) && $item->TIPO == 'Ave' ? 'selected' : ''; ?>>Ave</option>
                <option value="Reptil" <?php echo isset($item) && $item->TIPO == 'Reptil' ? 'selected' : ''; ?>>Reptil</option>
            </select><br><br>

            <label for="owner">Dueño:</label><br>
            <select class="form-control" name="idowner" id="owner">
                <?php foreach ($owners as $owner) : ?>
                    <option value="<?php echo $owner->ID; ?>" <?php echo isset($item) && $item->ID_DUENIO == $owner->ID ? 'selected' : ''; ?>><?php echo $owner->NOMBRE; ?></option>
                <?php endforeach; ?>
            <?php endif; ?>
            </select><br><br>


            <button type="submit" class="btn btn-primary"><?php echo isset($item) ? 'Actualizar' : 'Crear'; ?> <?php echo $itemType == 'pet' ? 'Mascota' : 'Dueño'; ?></button>
        </form>

        <script>
            const body = document.querySelector('body');
            const form = document.querySelector('.formCreateEdit');
            const btnSubmit = form.querySelector('button[type="submit"]');
            const itemType = form.getAttribute('id');
            const baseURL = body.getAttribute('data-base-url');
            const showNotification = (status, message) => {
                // Crea un nuevo div para la notificación
                const notification = document.createElement('div');
                // Añade las clases para los estilos
                notification.className = 'notification alert fade-out alert-' + status;
                // Añade el contenido de la notificación
                notification.innerHTML = '<i class="fas fa-' + (status === 'success' ? 'info-circle' : 'exclamation-triangle') + '"></i> ' + message;
                // Añade la notificación al cuerpo del documento
                document.body.appendChild(notification);
                // Después de 5 segundos, elimina la notificación
                setTimeout(function() {
                    document.body.removeChild(notification);
                }, 5000);
            }

            form.addEventListener('submit', async function(e) {
                try {
                    e.preventDefault();
                    const endpoint = form.getAttribute('action');
                    const formData = new FormData(form);

                    btnSubmit.disabled = true;
                    const response = await fetch(endpoint, {
                        method: 'POST',
                        body: formData
                    })
                    const data = await response.json();
                    showNotification(data.status, data.message);

                } catch (error) {
                    console.error('Error:', error);
                    showNotification("danger", "Error");
                } finally {
                    btnSubmit.disabled = false;
                   // resetea el formulario si no estoy editando
                   // para saber si estoy editando un elemento me fijo en el texto del botón submit que contenga la palabra "Crear"
                    if (btnSubmit.innerText.includes('Crear')) {
                        form.reset();
                    }
                     
                    

                }
            });
        </script>

        <?php require_once 'templates/footer.phtml' ?>