<?php require 'templates/header.phtml' ?>
<!-- <ul class="list-of-options">
<?php foreach($options as $option): ?>
    <li class="list-option">
        <div>
            <?php 
            switch ($option) {
                case 'Listado de Mascotas':
                    ?>
                        <a href='list-pets/'><?= $option ?></a>
                    <?php
                    break;
                case 'Listado de Dueños':
                    ?>
                        <a href='list-owners/'><?= $option ?></a>
                    <?php
                    break;
                case 'Listado de Mascotas por Dueño':
                    ?>
                        <form action = "pets-by-owner/"<?php ?> method="POST">
                            <label for="owner">Buscar mascotas del dueño:</label><br>
                            <select name="idowner" id="owner">
                                <?php foreach ($owners as $owner) : ?>
                                    <option value="<?php echo $owner->ID; ?>"> <?php echo $owner->NOMBRE ?> </option>
                                <?php endforeach; ?> 
                            </select>
                            <button type="submit"> Buscar </button>
                        </form>
                    <?php
                    break;      
            }
            ?>
        </div>
    </li>


<?php endforeach ?>
</ul> -->

<?php require_once 'templates/footer.phtml' ?>