<?php require_once 'templates/header.phtml' ?>

<form method="POST" action="auth">
    <div class="mb-3">
        <label for="user" class="form-label">Usuario</label>
        <input type="text" class="form-control" id="user" name="user" aria-describedby="emailHelp">
        <!-- <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div> -->
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Contraseña</label>
        <input type="password" class="form-control" id="password" name="password" required>
    </div>
    <!-- <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div> -->
    <button type="submit" class="btn btn-primary">Iniciar Sesión</button>
    <?php if ($error) : ?>
        <div class='error-login' role='alert'>
            <?= $error ?>
        </div>
    <?php endif ?>
</form>


<?php require_once 'templates/footer.phtml' ?>