<?php require_once './app/helpers/auth.helper.php' ?>
<nav>
    <div>
        <a href='../options'> Inicio </a>
    </div>
    <div>
        <a href="javascript:history.back()">Volver a la página anterior</a>
    </div>
    <!-- si estoy parado en list-pets entonces muestro botón crear  -->
    <?php if (AuthHelper::isLogged() && strpos($_SERVER['REQUEST_URI'], 'list-pets')) { ?>
        <div>
            <a href="../add-pet/">Crear Mascota</a>
        </div>
    <?php } ?>
    <?php if (AuthHelper::isLogged() && strpos($_SERVER['REQUEST_URI'], 'list-owners')) { ?>
        <div>
            <a href="../add-owner/">Crear Dueño</a>
        </div>
    <?php } ?>
    <div>
        <?php if (AuthHelper::isLogged()) { ?>
            <a href="../logout">Logout</a>
        <?php } else { ?>
            <a href="../login">Login</a>
        <?php } ?>
    </div>
</nav>