<?php require_once './app/helpers/auth.helper.php' ?>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Veterinaria</a>
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="home">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="list-owners">Dueños</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="list-pets">Mascotas</a>
            </li>
            <!-- <li class="nav-item">
                <a class="nav-link" href="#">About</a>
            </li> -->
        </ul>
        <form class="form-inline" method="GET" action="<?php (AuthHelper::isLogged()) ? 'logout' : 'login' ?>">
            <?php if (AuthHelper::isLogged()) { ?>
                <?php
                $username = $_SESSION['USERNAME'];
                ?>
                <a href="logout">Logout (<?= $username; ?>)</a>
                <!-- <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Logout (<?= $username; ?>)</button> -->
            <?php } else { ?>
                <a href="login">Login</a>
                <!-- <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Login</button> -->
            <?php } ?>
        </form>
    </div>
</nav>