<?php require_once './app/helpers/auth.helper.php' ?>

<?php
$current_page = basename($_SERVER['REQUEST_URI']);
$homeDir = dirname($_SERVER['PHP_SELF'])
?>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="<?= BASE_URL ?>">Veterinaria</a>
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item <?= $homeDir == "/" . $current_page ? "active" : "" ?>">
                <a class="nav-link" href="<?= BASE_URL ?>">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item <?= "list-owners" ==  $current_page ? "active" : "" ?>">
                <a class="nav-link" href="<?= BASE_URL ?>list-owners">Dueños</a>
            </li>
            <li class="nav-item <?= "list-pets" ==  $current_page ? "active" : "" ?>">
                <a class="nav-link" href="<?= BASE_URL ?>list-pets">Mascotas</a>
            </li>
        </ul>
        <form class="form-inline" method="GET" action="<?php (AuthHelper::isLogged()) ? 'logout' : 'login' ?>">
            <?php if (AuthHelper::isLogged()) { ?>
                <?php
                $username = $_SESSION['USERNAME'];
                ?>
                <a href="<?= BASE_URL ?>logout">Logout (<?= $username; ?>)</a>
                <!-- <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Logout (<?= $username; ?>)</button> -->
            <?php } else { ?>
                <a href="<?= BASE_URL ?>login">Login</a>
                <!-- <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Login</button> -->
            <?php } ?>
        </form>
    </div>
</nav>