<?php require_once 'templates/header.phtml' ?>

<?php if (empty($owners)) : ?>
    <div class="emptyContainer">
        <img src="<?= BASE_URL ?>assets/img/ownerPetEmpty.png" alt="Empty state" width="350">
        <?php
        $description = 'No hay dueños registrados.';
        $type = 'owner';
        require_once 'templates/emptyState.phtml'
        ?>
    </div>
<?php else : ?>

    <table class="table">
        <h2>Dueños</h2>
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Mail</th>
            </tr>
        </thead>
        <tbody>

            <?php foreach ($owners as $owner) : ?>
                <tr>
                    <td><?= $owner->ID ?></td>
                    <td><?= $owner->NOMBRE ?></td>
                    <td><?= $owner->MAIL ?> </td>
                    <td><a href="<?= BASE_URL ?>owner/<?= $owner->ID ?>" class="btn btn-info"> Ver</a></td>
                    <!-- si esta logueado puede eliminar o editar item -->
                    <?php if (AuthHelper::isLogged()) : ?>
                        <td><a href="<?= BASE_URL ?>owner-edit/<?= $owner->ID ?>" class="btn btn-primary"> Editar</a></td>
                        <td><a href="#" class="eliminar-item btn btn-danger" data-item-id="<?= $owner->ID ?>"> Eliminar</a></td>
                    <?php endif ?>
                </tr>

            <?php endforeach ?>
        </tbody>
    </table>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var eliminarLinks = document.querySelectorAll('.eliminar-item');

            eliminarLinks.forEach(function(enlace) {
                enlace.addEventListener('click', function(event) {
                    event.preventDefault();
                    var itemId = enlace.getAttribute('data-item-id');


                    Swal.fire({
                        title: '¿Estás seguro de que quieres eliminar a  <?= $owner->NOMBRE ?> ?',
                        text: "¡No podrás revertir esto!",
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonColor: '#d33',
                        cancelButtonColor: '#3085d6',
                        confirmButtonText: 'Si, eliminar!',
                        cancelButtonText: 'Cancelar'
                    }).then(async (result) => {
                        console.log(result);
                        if (result.isConfirmed) {
                            try {
                                const response = await fetch('<?= BASE_URL ?>owner-delete/' + itemId);
                                const data = await response.json();
                                if (data.status == 200) {
                                    Swal.fire(
                                        'Eliminado!',
                                        'El dueño se eliminó correctamente.',
                                        'success'
                                    ).then((result) => {
                                        window.location.href = '<?= BASE_URL ?>list-owners';
                                    });
                                    return;
                                }
                                if (data.status == 403) {
                                    Swal.fire(
                                        'No se puede eliminar!',
                                        'El dueño tiene mascotas asociadas.',
                                        'error'
                                    );
                                    return;
                                }


                            } catch (error) {
                                console.log(error);
                            }


                        }
                    })

                });
            });
        });
    </script>
<?php endif ?>
<?php require_once 'templates/footer.phtml' ?>