<?php require_once 'templates/header.phtml' ?>

<?php if (AuthHelper::isLogged()) : ?>
    <div class="fl-s">
        <a href="<?= BASE_URL ?>add-owner" class="btn btn-primary">Crear Dueño</a>
    </div>
<?php endif ?>

<?php if (empty($owners)) : ?>
    <?php
    $description = 'No hay dueños.';
    require_once 'templates/emptyState.phtml'
    ?>
<?php else : ?>

    <table class="table">
        <h2>Dueños:</h2>
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Mail</th>
            </tr>
        </thead>
        <tbody>

            <?php foreach ($owners as $owner) : ?>
                <tr>
                    <td><?= $owner->ID ?></td>
                    <td><?= $owner->NOMBRE ?></td>
                    <td><?= $owner->MAIL ?> </td>
                    <td><a href="<?= BASE_URL ?>owner/<?= $owner->ID ?>"> Ver</a></td>
                    <!-- si esta logueado puede eliminar o editar item -->
                    <?php if (AuthHelper::isLogged()) : ?>
                        <td><a href="<?= BASE_URL ?>owner-edit/<?= $owner->ID ?>"> Editar</a></td>
                        <td><a href="<?= BASE_URL ?>owner-delete/<?= $owner->ID ?>"> Eliminar</a></td>
                    <?php endif ?>
                </tr>

            <?php endforeach ?>
        </tbody>
    </table>
    <script>
        function eliminarElemento(id) {
            // Mostrar SweetAlert de confirmación
            Swal.fire({
                title: '¿Estás seguro?',
                text: 'Esta acción no se puede deshacer.',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Sí, eliminar',
                cancelButtonText: 'Cancelar'
            }).then((result) => {
                if (result.isConfirmed) {
                    // Aquí puedes realizar la lógica para eliminar el elemento con el ID proporcionado
                    // Puedes hacer una petición AJAX o redirigir a una página de PHP para manejar la eliminación.

                    // Ejemplo de redirección (ajusta según tus necesidades)
                    window.location.href = "<?= BASE_URL ?>pet-delete/" + id;
                }
            });
        }
    </script>
<?php endif ?>
<?php require_once 'templates/footer.phtml' ?>