<?php require_once 'templates/header.phtml' ?>
<?php if (empty($pets)) : ?>
    <?php
    $description = 'No hay mascotas.';
    require_once 'templates/emptyState.phtml'
    ?>
<?php else : ?>
    <table class="table">
        <h2>Mascotas: </h2>
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Años</th>
                <th>ID Dueño</th>
                <th>Nombre del dueño</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($pets as $pet) :
                $ownerid = $pet->ID_DUENIO;
                $ownerName = "No tiene dueño";
                foreach ($owners as $owner) {
                    if ($owner->ID == $ownerid) {
                        $ownerName = $owner->NOMBRE;
                    }
                }                
              
                
            ?>
                <tr>
                    <td><?= $pet->NOMBRE ?></td>
                    <td><?= $pet->EDAD ?></td>
                    <td><?= $pet->ID_DUENIO ?></td>
                    <td><?= $ownerName ?></td>
                    <td><a href="<?= BASE_URL ?>pet/<?= $pet->ID ?>"> Ver</a></td>
                    <!-- si esta logueado puede eliminar o editar item -->
                    <?php if (AuthHelper::isLogged()) : ?>
                        <td><a href="<?= BASE_URL ?>pet-edit/<?= $pet->ID ?>"> Editar</a></td>
                        <td><a href="<?= BASE_URL ?>pet-delete/<?= $pet->ID ?>"> Eliminar</a></td>
                    <?php endif ?>
                </tr>

            <?php endforeach ?>
        </tbody>
    </table>
<?php endif ?>
<?php require_once 'templates/footer.phtml' ?>