<?php require_once 'templates/header.phtml' ?>
<?php require_once 'templates/navbar.phtml' ?>

<table class="table">
    <h2>Mascotas de <?= $owner->NOMBRE ?> :</h2>
    <thead>
        <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Edad </th>
            <th>Peso </th>
            <th>Tipo </th>
        </tr>
    </thead>
    <tbody>
<?php foreach($pets as $pet): ?>
    <tr>
        <td><?= $pet->ID ?></td>
        <td><?= $pet->NOMBRE ?></td>
        <td><?= $pet->EDAD ?></td>
        <td><?= $pet->PESO ?></td>
        <td><?= $pet->TIPO ?></td>
        <td><a href="../pet/<?= $pet->ID?>"> Ver en detalle</a></td>
    </tr>

<?php endforeach ?>

    </tbody>    
</table>

<?php require 'templates/footer.phtml' ?>