<?php require_once 'templates/header.phtml' ?>
<?php if (empty($pets)) : ?>
    <?php
    $description = 'No hay mascotas.';
    require_once 'templates/emptyState.phtml'
    ?>
<?php else : ?>
    <table class="table">
        <h2>Mascotas: </h2>
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Años</th>
                <th>ID Dueño</th>
                <th>Nombre del dueño</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($pets as $pet) :
                $petowner = $pet->ID_DUENIO - 1;
                $ownerid = $owners[$petowner];
            ?>
                <tr>
                    <td><?= $pet->NOMBRE ?></td>
                    <td><?= $pet->EDAD ?></td>
                    <td><?= $pet->ID_DUENIO ?></td>
                    <td><?= $ownerid->NOMBRE ?></td>
                    <td><a href="../pet/<?= $pet->ID ?>"> Ver</a></td>
                    <!-- si esta logueado puede eliminar o editar item -->
                    <?php if (AuthHelper::isLogged()) : ?>
                        <td><a href="../pet-edit/<?= $pet->ID ?>"> Editar</a></td>
                        <td><a href="../pet-delete/<?= $pet->ID ?>"> Eliminar</a></td>
                    <?php endif ?>
                </tr>

            <?php endforeach ?>
        </tbody>
    </table>
<?php endif ?>
<?php require_once 'templates/footer.phtml' ?>