<?php if (empty($pets)) : ?>
    <style>
        .emptyTable {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            /* margin-top: 20px; */
        }
    </style>
    <div class="emptyTable">
        <img src="<?= BASE_URL ?>assets/img/emptyPet.png" alt="Empty state" width="350">
        <?php
        $description = 'Aún no agregaste mascotas para este dueño.';
        $type = 'pet';
        $owners= $owner;
        require_once 'templates/emptyState.phtml'
        ?>
    </div>
<?php else : ?>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Edad </th>
                <th>Peso </th>
                <th>Tipo </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($pets as $pet) : ?>
                <tr>
                    <td><?= $pet->ID ?></td>
                    <td><?= $pet->NOMBRE ?></td>
                    <td><?= $pet->EDAD ?></td>
                    <td><?= $pet->PESO ?></td>
                    <td><span class="badge badge-pill badge-info"><?= $pet->TIPO ?></span></td>
                    <td><a href="<?= BASE_URL ?>pet/<?= $pet->ID ?>"> Ver en detalle</a></td>
                </tr>

            <?php endforeach ?>

        </tbody>
    </table>
<?php endif ?>