<!-- Página de registro -->
<!-- La página de registro es muy similar a la de inicio de sesión, pero en lugar de un formulario de inicio de sesión, tenemos un formulario de registro. -->
<!-- El formulario de registro tiene los siguientes campos: -->
<!-- Correo -->
<!-- Contraseña -->
<!-- Confirmar Contraseña -->
<?php require_once 'templates/header.phtml' ?>
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="text-center">Registro</h3>
                </div>
                <div class="card-body">
                    <!-- Formulario de Registro -->
                    <form class="formSubmitLogin" method="POST" action="register">
                        <div class="form-group">
                            <label for="user">Usuario (email):</label>
                            <input type="text" class="form-control" id="user" name="user" aria-autocomplete="none" >
                        </div>
                        <div class="form-group">
                            <label for="password">Contraseña:</label>
                            <input type="password" class="form-control" id="password" name="password" aria-autocomplete="none">
                        </div>
                        <div class="form-group">
                            <label for="password">Confirmar Contraseña:</label>
                            <input type="password" class="form-control" id="password2" name="password2" aria-autocomplete="none">
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Registrarse</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<?php require_once 'templates/footer.phtml' ?>