<?php require_once 'templates/header.phtml' ?>
<div class="go-back">
    <a href="javascript:history.back()" class="btn btn-outline-primary">Volver a la página anterior</a>
</div>
<div class="card" style="width: 18rem;">
    <div class="card-body">
        <h2 class="card-title"><?= $owner->NOMBRE ?></h2>
        <h6 class="card-subtitle mb-2 text-muted"><?= $owner->MAIL ?></h6>
        <p class="card-text"> <?= $owner->TELEFONO ?></p>
        <!-- <a href="#" class="card-link">Card link</a>
        <a href="#" class="card-link">Another link</a> -->
    </div>
</div>
<div style="margin-top: 50px;">
    <h3>Mascotas </h3>
    <hr/>
    <?php require 'templates/petsByOwner.phtml' ?>
</div>

<?php require 'templates/footer.phtml' ?>