<?php require_once 'templates/header.phtml' ?>

<div class="go-back">
    <a href="javascript:history.back()" class="btn btn-outline-primary">Volver a la página anterior</a>
</div>
<table class="table">
    <h2> <?= $pet->NOMBRE ?></h2>
    <thead>
        <tr>
            <th>Id</th>
            <th>Edad</th>
            <th>Peso</th>
            <th>Tipo</th>
            <th>Id del dueño</th>
            <th>Nombre del dueño</th>
        </tr>
    </thead>
    <tbody>

        <tr>
            <td><?= $pet->ID ?></td>
            <td><?= $pet->EDAD ?> </td>
            <td><?= $pet->PESO ?> </td>
            <td><?= $pet->TIPO ?> </td>
            <td><?= $pet->ID_DUENIO ?> </td>
            <td><?= $owner->NOMBRE ?></td>
        </tr>

    </tbody>
</table>


<?php require 'templates/footer.phtml' ?>