<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Veterinaria</title>
    <link rel="stylesheet" type="text/css" href="css/style.css">
</head>
<body>
    <div class="header">
        <div>
            <?php if (!isset($_SESSION['ID_USER'])) {
                ?> <p> Estas Logueado </p> 
            <?php
            }
            
            ?>
            <h1 class="header-titulo"> Veterinaria</h1>
        </div>
    </div>
    


    <!-- Inicio Main Container -->

    <div class="main-container">