<?php require_once 'templates/header.phtml' ?>

<h2>Iniciar Sesión</h2>
    <form method="POST" action="auth">
        <label for="user">Usuario:</label>
        <input type="text" id="user" name="user" required><br>

        <label for="password">Contraseña:</label>
        <input type="password" id="password" name="password" required><br>

        <button type="submit" class="btn-login"> Iniciar Sesión </button>

        <?php if ($error) : ?>
            <div class='error-login' role='alert'>
                <?= $error ?>
            </div> 
        <?php endif ?>

    </form>


<?php require_once 'templates/footer.phtml' ?>