<?php require_once 'templates/buttonHome.phtml' ?>
<?php require_once 'templates/header.phtml' ?>

<link rel="stylesheet" type="text/css" href="../css/style.css">

<table class="table">
    <h2>Mascotas: </h2>
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Años</th>
            <th>ID Dueño</th>
            <th>Nombre del dueño</th>
        </tr>
    </thead>
    <tbody>
<?php foreach($pets as $pet): 
    $petowner = $pet->ID_DUENIO - 1;
    $ownerid = $owners[$petowner];
    ?>
    <tr>
        <td><?= $pet->NOMBRE ?></td>
        <td><?= $pet->EDAD ?></td>
        <td><?= $pet->ID_DUENIO ?></td>
        <td><?= $ownerid->NOMBRE ?></td>
        <td><a href="../pet/<?= $pet->ID?>"> Ver en detalle</a></td>
    </tr>

<?php endforeach ?>
    </tbody>    
</table>

<!-- si pongo el footer el owners que se agrega despues queda afuera. require 'templates/footer.phtml'  -->