<?php require_once 'templates/buttonBack.phtml' ?>
<?php require_once 'templates/header.phtml' ?>

<link rel="stylesheet" type="text/css" href="../css/style.css">
<table class="table-pets">
    <h2>Mascotas: </h2>
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Años</th>
            <th>ID Dueño</th>
        </tr>
    </thead>
    <tbody>
<?php foreach($pets as $pet): ?>
    <tr>
        <td><?= $pet->NOMBRE ?></td>
        <td><?= $pet->EDAD ?></td>
        <td><?= $pet->ID_DUENIO ?></td>
    </tr>

<?php endforeach ?>
    </tbody>    
</table>
